---
abstract: 'Automate Stratopan releases with Dist::Zilla'
author:
  - 'Mike Friedman <friedo@friedo.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-UploadToStratopan
requires:
  Dist::Zilla::Role::Releaser: '0'
  LWP::Protocol::https: '0'
  Mojo::DOM: '0'
  Mojo::UserAgent: '0'
  Moose: '0'
resources:
  repository: git://github.com/friedo/dzil-upload-to-stratopan.git
version: '0.012'
